backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "[add] {{collection}} “{{slug}}”"
    update: "[update] {{collection}} “{{slug}}”"
    delete: "[delete] {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/media
public_folder: /media

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "blog",
        }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Title, name: title }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: Body, name: body, widget: markdown }
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Category",
          name: "category",
          widget: "hidden",
          default: "pages",
        }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Title, name: title }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: Body, name: body, widget: markdown }
